# Simple docker complse override configuration file for chapter4/ application

# .env contem as variáveis HOSTIP
# para conferir se está tudo certo
# docker-compose -f .\docker-compose-example.yml config


version: '3'
services:

  redis:
    image: redis
    volumes:
      - ${PASTA_REDIS}:/data
    ports:
      - 6379:6379

  mongodb:
    image: mongo
    volumes:
      - ${PASTA_MONGO}:/data/db
    ports:
      - 27017:27017

  mosca:
    image: matteocollina/mosca
    volumes:
      - ${PASTA_MOSCA}:/db
    ports:
      - 1883:1883
      - 80:80

  publisher:
    build: publisher
    environment:
    - MQTT_HOST=${HOSTIP}
    - REDIS_HOST=${HOSTIP}
    - MONGO_HOST=${HOSTIP}
    ports:
      - 3000:3000

  subscriber:
    build: subscriber
    environment:
    - MQTT_HOST=${HOSTIP}
    - REDIS_HOST=${HOSTIP}
    - MONGO_HOST=${HOSTIP}

